name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY_GOOGLE_REGISTRY }}
          username: _json_key
          password: ${{ secrets.DOCKER_REGISTRY_GOOGLE_JSON_KEY }}

      - name: Build and push Docker image for back
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_GOOGLE_REGISTRY }}/${{ vars.DOCKER_REGISTRY_GOOGLE_PROJECT }}/singer-tap-ga4:${{ github.ref_name }}